### ISSUE TITLE
Plugin Folder

### ISSUE THREAD

**Issue by KleinCrafter** [brunyman/MysqlInventoryBridge#2]
Starting a Server with `java -jar spigot.jar -P /home/mcserver/plugins/plugins-1.12` the Plugin broke:

> [15:55:25] [Server thread/INFO]: [MysqlInventoryBridge] Enabling MysqlInventoryBridge v2.1.1
[15:55:25] [Server thread/INFO]: [MysqlInventoryBridge] No config file found! Creating new one...
[15:55:25] [Server thread/INFO]: [MysqlInventoryBridge] Loading the config file...
[15:55:25] [Server thread/ERROR]: [MysqlInventoryBridge] Could not load the config file! You need to regenerate the config! Error: plugins/MysqlInventoryBridge/config.yml (No such file or directory)
[15:55:25] [Server thread/WARN]: java.io.FileNotFoundException: plugins/MysqlInventoryBridge/config.yml (No such file or directory)
[15:55:25] [Server thread/WARN]:        at java.io.FileInputStream.open0(Native Method)
[15:55:25] [Server thread/WARN]:        at java.io.FileInputStream.open(FileInputStream.java:195)
[15:55:25] [Server thread/WARN]:        at java.io.FileInputStream.<init>(FileInputStream.java:138)
[15:55:25] [Server thread/WARN]:        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128)
[15:55:25] [Server thread/WARN]:        at net.craftersland.bridge.inventory.ConfigHandler.loadConfig(ConfigHandler.java:26)
[15:55:25] [Server thread/WARN]:        at net.craftersland.bridge.inventory.ConfigHandler.<init>(ConfigHandler.java:11)
[15:55:25] [Server thread/WARN]:        at net.craftersland.bridge.inventory.Inv.onEnable(Inv.java:38)
[15:55:25] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[15:55:25] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[15:55:25] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[15:55:25] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
[15:55:25] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
[15:55:25] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:206)
[15:55:25] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[15:55:25] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)
[15:55:25] [Server thread/INFO]: [MysqlInventoryBridge] ProtocolLib dependency found.
[15:55:25] [Server thread/INFO]: [MysqlInventoryBridge] Data save task is enabled.
[15:55:25] [Server thread/INFO]: [MysqlInventoryBridge] Connecting to the database...
[15:55:25] [Server thread/INFO]: [MysqlInventoryBridge] Database connection successful!
>[15:55:25] [Server thread/INFO]: [MysqlInventoryBridge] MysqlInventoryBridge loaded successfully!

**Comment by brunyman** [comment]
Fixed, thanks!
